SELECT * FROM Witcher

DROP PROCEDURE GetTablesList;

CREATE PROCEDURE GetTablesList AS
BEGIN
	SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE = 'BASE TABLE'
END;

DROP PROCEDURE GetKillByID;
CREATE PROCEDURE GetKillByID(@id INT, @Kill NVARCHAR OUTPUT) AS
BEGIN
	SET @Kill = (SELECT NumberOfKills FROM Witcher
			   WHERE Id = @id)
END;